# game_data.py
# This file contains all the prompts and data for the party games.
# You can easily add, remove, or edit prompts here without touching the bot logic.

TRUTH_OR_DARE_DATA = {
    "Classic & Funny": {
        "truth": [
            "What is your biggest irrational fear?",
            "What is the most embarrassing thing you've ever done in public?",
            "What is a secret you've never told your parents?",
            "What is the weirdest thing you've ever eaten?",
            "If you could swap lives with anyone for a day, who would it be?",
            "What is the worst lie you've ever told?",
            "What song do you secretly love but would never admit?",
            "What is the most childish thing you still do?",
            "Have you ever pretended to be sick to get out of something?",
            "What is your most awkward moment from school?",
            "What is something you're terrible at but wish you were good at?",
            "What is the strangest dream you've ever had?",
            "What is your guilty pleasure TV show or movie?",
            "Have you ever walked into a glass door or wall?",
            "What is the worst haircut you've ever had?",
            "What is the most embarrassing thing in your search history?",
            "Have you ever accidentally sent a text about someone to that person?",
            "What is your worst habit that you can't break?",
            "What is the most expensive thing you've broken?",
            "Have you ever laughed so hard you peed a little?",
            "What is the weirdest thing you've done when you thought no one was watching?",
            "What is your most embarrassing nickname?",
            "Have you ever been caught talking to yourself?",
            "What is the worst gift you've ever given someone?",
            "What is something you did as a kid that still makes you cringe?",
            "Have you ever stolen something and not gotten caught?",
            "What is the dumbest argument you've ever had?",
            "What is your most ridiculous fear?",
            "Have you ever had a paranormal experience?",
            "What is the worst date you've ever been on?",
            "What is something you pretend to understand but actually don't?",
            "Have you ever been rejected? What happened?",
            "What is the most embarrassing thing you've worn?",
            "What is your most used excuse?",
            "Have you ever cheated in a game?",
            "What is the strangest place you've fallen asleep?",
            "What is the most awkward text you've received?",
            "Have you ever been caught in a lie?",
            "What is your worst bathroom emergency story?",
            "What is the most random thing in your room right now?",
            "Have you ever had a crush on a fictional character?",
            "What is the worst advice you've ever given?",
            "What is your most embarrassing auto-correct fail?",
            "Have you ever eaten something off the floor?",
            "What is the strangest rumor you've heard about yourself?",
            "What is your most ridiculous purchase?",
            "Have you ever waved at someone who wasn't waving at you?",
            "What is your most embarrassing talent?",
            "What is the worst thing you've done out of boredom?",
            "Have you ever forgotten someone's name immediately after meeting them?"
        ],
        "dare": [
            "Do 15 pushups right now and send a video!",
            "Speak in an accent for the next 3 rounds.",
            "Let the group dictate what you post on your social media story.",
            "Eat a spoonful of a condiment (mustard, hot sauce, etc.).",
            "Try to lick your elbow for 30 seconds.",
            "Do your best impression of a celebrity until someone guesses it.",
            "Talk in third person for the next 5 minutes.",
            "Let someone draw on your face with a marker.",
            "Attempt to breakdance for 30 seconds.",
            "Speak only in song lyrics for the next 3 rounds.",
            "Do your best interpretive dance of your favorite movie.",
            "Let the group choose your profile picture for 24 hours.",
            "Call a random contact and speak only in gibberish for 30 seconds.",
            "Wear a sock on your hand as a puppet for the next 5 rounds.",
            "Try to sell an imaginary product to the group for 60 seconds.",
            "Let someone give you a wedgie (if you're wearing appropriate clothing).",
            "Do your best runway walk across the room.",
            "Try to touch your nose with your tongue.",
            "Let the group create a new handshake for you.",
            "Attempt to do the splits (safely!).",
            "Make up a commercial for an imaginary product and perform it.",
            "Let someone style your hair however they want.",
            "Try to keep a straight face while everyone makes funny faces at you.",
            "Do your best impression of an animal until someone guesses it.",
            "Let the group pick a word you must say after every sentence for 5 minutes.",
            "Try to juggle 3 random objects.",
            "Let someone tickle you for 30 seconds without laughing.",
            "Do 20 jumping jacks while singing your favorite song.",
            "Try to walk in a straight line with your eyes closed.",
            "Let the group choose your outfit for the next round.",
            "Attempt to do a cartwheel (safely!).",
            "Make up a rap about the person to your left.",
            "Try to balance a book on your head while walking across the room.",
            "Let someone paint your nails however they want.",
            "Do your best impression of a baby being born.",
            "Try to do 10 burpees in a row.",
            "Let the group choose a new nickname for you for the rest of the game.",
            "Attempt to do the worm dance move.",
            "Try to hold a plank for 1 minute.",
            "Let someone give you a makeover with their eyes closed.",
            "Do your best opera singing voice for 30 seconds.",
            "Try to touch your toes without bending your knees.",
            "Let the group decide what you must wear on your head for 3 rounds.",
            "Attempt to do a handstand against a wall for 10 seconds.",
            "Make up a poem about the player across from you and recite it.",
            "Try to keep your eyes crossed for 30 seconds.",
            "Let someone write a message on your forehead with a washable marker.",
            "Do your best robot dance for 30 seconds.",
            "Try to do a headstand (safely!).",
            "Let the group choose a pose you must hold until your next turn."
        ]
    },
    "Friends": {
        "truth": [
            "Who in this chat would you trust with your phone password?",
            "What is the most annoying habit your best friend has?",
            "Have you ever lied to get out of hanging out with someone here?",
            "What's a rumor you've heard about yourself?",
            "Who was your first crush in this friend group?",
            "What is something you've stolen from a friend?",
            "Which friend would you call to help you hide a body?",
            "What is the pettiest reason you've ended a friendship?",
            "Have you ever talked behind someone's back in this group?",
            "Who is most likely to embarrass you in public?",
            "What secret do you know about someone here?",
            "Who is the worst at keeping secrets in this group?",
            "What is the most annoying thing about the person to your left?",
            "Have you ever had a dream about someone in this group?",
            "Who would you save first in a zombie apocalypse?",
            "What is something you've always wanted to tell someone here but haven't?",
            "Who is most likely to cancel plans last minute?",
            "What is the weirdest thing you've seen a friend do?",
            "Have you ever copied someone's homework?",
            "Who is your favorite person in this group and why?",
            "What is the most embarrassing thing you've done in front of these friends?",
            "Who would you not invite to your wedding?",
            "What is a habit you wish someone in this group would stop?",
            "Have you ever been jealous of someone here?",
            "Who is most likely to get arrested?",
            "What is the worst advice you've received from a friend?",
            "Who do you think has changed the most since you met them?",
            "Have you ever pretended to like a gift from someone here?",
            "Who is most likely to forget your birthday?",
            "What is something you know about someone that they don't know you know?",
            "Who would you choose as your emergency contact?",
            "What is the most childish thing someone in this group does?",
            "Have you ever been mad at someone here but pretended you weren't?",
            "Who is most likely to spill a secret?",
            "What is your honest opinion of someone's outfit right now?",
            "Who would win in an argument between you and the person to your right?",
            "What is the most annoying text habit someone here has?",
            "Have you ever screenshot a conversation with someone here?",
            "Who is most likely to be late to their own funeral?",
            "What is something you judge someone in this group for?",
            "Who would you choose as your partner in a reality show?",
            "What is the worst thing you've said about someone here?",
            "Have you ever intentionally ignored someone's message?",
            "Who is most likely to become famous?",
            "What is your least favorite thing about this group chat?",
            "Who would you trust to set you up on a blind date?",
            "Have you ever lied about your plans to avoid someone here?",
            "Who is most likely to win the lottery and lose the ticket?",
            "What is the most embarrassing thing you know about someone here?",
            "Who would you choose as your lawyer if you were in trouble?",
            "Have you ever had a crush on a friend's sibling?"
        ],
        "dare": [
            "Send a screenshot of your last 3 text messages.",
            "Call a random contact and sing 'Happy Birthday' to them.",
            "Let the person to your right style your hair.",
            "Show the last photo in your camera roll.",
            "Text your mom 'I need to tell you something serious' and wait 5 mins before replying.",
            "Let the group send a message to anyone in your contacts.",
            "Reveal your screen time for the past week.",
            "Do an impression of each person in the group.",
            "Let someone go through your photos and pick one to post.",
            "Speak only in questions for the next 3 rounds.",
            "Send a voice note to your crush saying 'I've been thinking about you'.",
            "Let the group choose your wallpaper for a day.",
            "Show your most recent search history.",
            "Call a friend and tell them you're moving to Antarctica.",
            "Let someone read your last 5 text messages aloud.",
            "Post 'I love pineapple on pizza' on your social media if you don't.",
            "Send a selfie with your ugliest face to the 5th person in your contacts.",
            "Let the group choose who you must prank call.",
            "Reveal your last Instagram search.",
            "Send a message to your ex saying 'We need to talk'.",
            "Let someone borrow your phone and text anyone they want.",
            "Show the group your most embarrassing photo.",
            "Call a random number and try to make a friend.",
            "Let the group choose your outfit for the next day.",
            "Send a voice note of you singing a song chosen by the group.",
            "Reveal who your most recent call was with.",
            "Let someone post a story on your social media.",
            "Text your best friend 'I have a confession to make' and wait 10 minutes.",
            "Show your YouTube search history.",
            "Let the group choose a filter you must use on all photos for 24 hours.",
            "Send a message to someone saying 'I had a dream about you last night'.",
            "Let someone rename all your contacts for an hour.",
            "Call your parents and tell them you're dropping out (if applicable).",
            "Show the group your saved memes.",
            "Let the group choose your profile picture for a week.",
            "Send a flirty text to someone random in your contacts.",
            "Reveal your most-played song on Spotify/Apple Music.",
            "Let someone scroll through your camera roll for 2 minutes.",
            "Text a friend 'I know what you did' and don't explain.",
            "Show the group your recently deleted photos.",
            "Let the group choose a contact for you to send a selfie to.",
            "Call a restaurant and ask if they serve dinosaur meat.",
            "Reveal your screen time breakdown by app.",
            "Let someone change your phone language for an hour.",
            "Send a message to your crush asking if they believe in aliens.",
            "Show your Amazon order history.",
            "Let the group choose a contact to call and confess your love to.",
            "Text your sibling 'I'm adopted and you're not' as a joke.",
            "Reveal your most embarrassing app on your phone.",
            "Let someone write a caption on your next social media post."
        ]
    },
    "Couples": {
        "truth": [
            "What was your very first impression of me?",
            "What is your favorite memory of us so far?",
            "What is one thing you wish we did more often?",
            "When did you first realize you had feelings for me?",
            "What is the most attractive thing I do without realizing it?",
            "What is your biggest insecurity in our relationship?",
            "Have you ever checked my phone without me knowing?",
            "What is something I do that annoys you?",
            "Who said 'I love you' first?",
            "What is your favorite physical feature of mine?",
            "What is something you're afraid to tell me?",
            "Have you ever lied to me about something important?",
            "What is your favorite thing about our relationship?",
            "Do you see a future with me? Describe it.",
            "What is the most romantic thing I've ever done for you?",
            "What is something you want us to try together?",
            "Have you ever been jealous of someone in my life?",
            "What is your favorite nickname for me?",
            "What is the best gift I've ever given you?",
            "What is something I do that makes you feel loved?",
            "Have you ever doubted our relationship?",
            "What is your favorite date we've been on?",
            "What is something you wish I understood about you?",
            "Have you ever kept a secret from me?",
            "What is your favorite thing I cook or make for you?",
            "What is the most vulnerable moment we've shared?",
            "Have you ever compared me to an ex?",
            "What is your love language?",
            "What is something you want to improve about yourself for us?",
            "Have you ever thought about breaking up?",
            "What is your favorite non-physical thing about me?",
            "What is the most meaningful thing I've said to you?",
            "Have you ever been mad at me but didn't tell me?",
            "What is your favorite way we spend time together?",
            "What is something you admire about me?",
            "Have you ever felt neglected by me?",
            "What is your favorite inside joke we have?",
            "What is the most supportive thing I've done for you?",
            "Have you ever been tempted to cheat?",
            "What is your favorite thing about waking up next to me?",
            "What is something you want to ask me but haven't?",
            "What is the most fun we've ever had together?",
            "Have you ever lied about being okay when you weren't?",
            "What is your favorite photo of us?",
            "What is something you've learned from me?",
            "Have you ever been embarrassed by something I did?",
            "What is your ideal anniversary celebration?",
            "What is the most comforting thing I do?",
            "Have you ever had a dream about us breaking up?",
            "What is one thing you never want to change about us?"
        ],
        "dare": [
            "Give me a genuine, detailed compliment right now.",
            "Send a voice note singing a song of my choice.",
            "Hold my hand (or hug me) for the next 3 rounds.",
            "Recreate our first kiss right now.",
            "Let me look through your photo gallery for 1 minute.",
            "Write me a poem and read it aloud.",
            "Give me a piggyback ride around the room.",
            "Feed me something without using your hands.",
            "Whisper something sweet in my ear.",
            "Take a silly selfie together and post it.",
            "Give me a 2-minute massage.",
            "Tell me your favorite thing about me in detail.",
            "Let me pick your outfit for our next date.",
            "Draw a picture of us and show everyone.",
            "Give me a kiss on every part of my face.",
            "Let me paint your nails however I want.",
            "Serenade me with your favorite love song.",
            "Write 'I love you' on my back with your finger and let me guess.",
            "Let me style your hair however I want.",
            "Give me a foot massage for 3 minutes.",
            "Tell me the story of how we met from your perspective.",
            "Let me do your makeup (if applicable) or draw on your face.",
            "Dance with me to our song (or any slow song).",
            "Give me a back hug for 1 minute.",
            "Let me choose your profile picture for a day.",
            "Read me a love letter you write right now.",
            "Give me eskimo kisses for 30 seconds.",
            "Let me pick a movie for us to watch tonight.",
            "Make me a playlist of songs that remind you of us.",
            "Give me a forehead kiss and tell me I'm yours.",
            "Let me take a photo of you sleeping later.",
            "Cook me your best dish or make me a drink.",
            "Give me a butterfly kiss (eyelashes).",
            "Let me choose your next 3 text message responses.",
            "Tell me what you're most grateful for about me.",
            "Give me a long, tight hug for 30 seconds.",
            "Let me braid or style your hair.",
            "Whisper 3 things you love about me.",
            "Give me a kiss for every month we've been together.",
            "Let me pick your phone wallpaper for a week.",
            "Make up a nickname for me and use it for the rest of the game.",
            "Give me a shoulder massage while telling me about your day.",
            "Let me choose what we eat for our next meal together.",
            "Write our initials in a heart and send it to me.",
            "Give me a compliment every time I snap for 5 minutes.",
            "Let me take control of the TV/remote for the evening.",
            "Tell me your favorite memory of us in detail.",
            "Give me a slow dance right here, right now.",
            "Let me pick your social media bio for 24 hours.",
            "Give me a genuine promise about our future together."
        ]
    },
    "Party & Kids": {
        "truth": [
            "What is your favorite cartoon character of all time?",
            "If you could have any superpower, what would it be?",
            "What is the silliest thing you believed as a child?",
            "If you were an animal, which one would you be and why?",
            "What is your go-to karaoke song?",
            "What is the worst gift you've ever received?",
            "If you could be invisible for a day, what would you do?",
            "What is your favorite ice cream flavor?",
            "Who is your celebrity crush?",
            "What is the funniest joke you know?",
            "What is your favorite board game?",
            "If you could live anywhere in the world, where would it be?",
            "What is your favorite holiday?",
            "If you could meet any historical figure, who would it be?",
            "What is your favorite pizza topping?",
            "What is the best book you've ever read?",
            "If you could be any age forever, what age would you choose?",
            "What is your favorite thing to do on weekends?",
            "What is the coolest thing you've ever built or made?",
            "If you could have any pet, what would you choose?",
            "What is your favorite color and why?",
            "What is the best vacation you've ever been on?",
            "If you could be a character in any movie, who would you be?",
            "What is your favorite subject in school?",
            "What is the most interesting fact you know?",
            "If you could eat only one food forever, what would it be?",
            "What is your favorite season?",
            "What is the bravest thing you've ever done?",
            "If you could time travel, where would you go?",
            "What is your favorite sport to play or watch?",
            "What is the best present you've ever received?",
            "If you could be famous for one thing, what would it be?",
            "What is your favorite thing about your best friend?",
            "What is the most delicious thing you've ever eaten?",
            "If you could have any job in the world, what would it be?",
            "What is your favorite video game?",
            "What is the kindest thing you've ever done?",
            "If you could change your name, what would you pick?",
            "What is your favorite thing to do outside?",
            "What is the most amazing place you've ever visited?",
            "If you could talk to animals, what would you ask them?",
            "What is your favorite type of music?",
            "What is the most important lesson you've learned?",
            "If you could invent something, what would it do?",
            "What is your favorite thing about yourself?",
            "What is the best dream you've ever had?",
            "If you could be best friends with any cartoon character, who would it be?",
            "What is your favorite thing to do with your family?",
            "What is the most beautiful thing you've ever seen?",
            "If you had a million dollars, what would you buy first?",
            "What is your favorite memory from the past year?"
        ],
        "dare": [
            "Do your best animal impression until someone guesses it.",
            "Dance with no music for 1 minute.",
            "Talk without closing your mouth for the next 2 rounds.",
            "Act like a chicken until your next turn.",
            "Try to juggle 3 items of the group's choosing.",
            "Balance a book on your head for 2 rounds.",
            "Do the worm dance move.",
            "Make up a rap about the person to your left.",
            "Hold a funny face for 30 seconds without laughing.",
            "Walk across the room like a model on a runway.",
            "Do your best robot impression for 30 seconds.",
            "Try to hop on one foot while spinning in a circle.",
            "Make up a short story using 5 random words from the group.",
            "Act like your favorite cartoon character for 1 minute.",
            "Try to do a cartwheel or somersault safely.",
            "Make animal sounds that spell out your name.",
            "Walk like a crab across the room and back.",
            "Try to keep a balloon in the air for 30 seconds.",
            "Make up a handshake with the person across from you.",
            "Do your best superhero pose and hold it for 30 seconds.",
            "Try to touch your nose with your tongue.",
            "Make up a new dance move and teach it to everyone.",
            "Walk backwards for your next 3 turns.",
            "Try to say the alphabet backwards as fast as you can.",
            "Make up a commercial for your favorite toy.",
            "Do your best impression of a baby learning to walk.",
            "Try to stack 5 items in 30 seconds.",
            "Make up a song about your favorite food.",
            "Act like a statue until your next turn.",
            "Try to do 10 jumping jacks while saying a tongue twister.",
            "Make up a magic trick and perform it.",
            "Walk with your knees touching for 1 minute.",
            "Try to keep your eyes closed while walking to the door and back.",
            "Make up a story where you're the main hero.",
            "Do your best impression of a roller coaster.",
            "Try to balance on one leg for 1 minute.",
            "Make up a new word and define it.",
            "Act like you're underwater for 30 seconds.",
            "Try to hop through an obstacle course the group creates.",
            "Make up a cheer for the group.",
            "Do your best impression of a robot malfunctioning.",
            "Try to draw something with your eyes closed.",
            "Make up a rap about your favorite hobby.",
            "Act like you're in slow motion for 1 minute.",
            "Try to do 5 spins without getting dizzy.",
            "Make up a secret handshake with everyone in the group.",
            "Do your best impression of a famous singer.",
            "Try to walk in a straight line with a book on your head.",
            "Make up a poem about your favorite season.",
            "Act like a news reporter interviewing someone in the group."
        ]
    },
    "Spicy (18+)": {
        "truth": [
            "What is your biggest turn-on?",
            "Have you ever had a crush on someone in this room?",
            "What is the most adventurous place you've ever hooked up?",
            "What is a fantasy you've never told anyone about?",
            "Have you ever sent a risky text to the wrong person?",
            "What is your favorite position?",
            "Have you ever had a one-night stand?",
            "What is the kinkiest thing you've ever done?",
            "Who was your best sexual partner and why?",
            "Have you ever been caught in the act?",
            "What is your biggest sexual fantasy?",
            "Have you ever used toys?",
            "What is the most public place you've been intimate?",
            "Have you ever had a friends-with-benefits arrangement?",
            "What is your favorite body part on a partner?",
            "Have you ever had phone sex?",
            "What is the most embarrassing thing that's happened during sex?",
            "Have you ever role-played?",
            "What is your favorite time of day to be intimate?",
            "Have you ever had a threesome?",
            "What is the dirtiest text you've ever sent?",
            "Have you ever watched adult content with a partner?",
            "What is your favorite type of foreplay?",
            "Have you ever been tied up or tied someone up?",
            "What is the longest you've gone without sex?",
            "Have you ever had a pregnancy scare?",
            "What is your favorite thing to wear to bed?",
            "Have you ever had sex in a car?",
            "What is the most risque photo you've ever sent?",
            "Have you ever used food during intimacy?",
            "What is your biggest sexual insecurity?",
            "Have you ever faked an orgasm?",
            "What is the most unusual place you've fantasized about?",
            "Have you ever had a sexual dream about someone here?",
            "What is your favorite way to be teased?",
            "Have you ever been to a strip club?",
            "What is the most dominant or submissive you've been?",
            "Have you ever made a sex tape?",
            "What is your favorite type of lingerie?",
            "Have you ever had shower sex?",
            "What is the most erotic book or movie you've experienced?",
            "Have you ever used handcuffs?",
            "What is your favorite way to initiate intimacy?",
            "Have you ever had a sexual encounter with someone much older or younger?",
            "What is the most sensitive spot on your body?",
            "Have you ever had a lap dance?",
            "What is your opinion on open relationships?",
            "Have you ever been intimate while someone else was in the room?",
            "What is the most creative place you've had sex?",
            "Have you ever used ice or hot wax?",
            "What is your ultimate sexual fantasy you haven't tried yet?"
        ],
        "dare": [
            "Send a flirty text to the last person you texted.",
            "Describe your ideal romantic evening in vivid detail.",
            "Let the group give you a new, temporary nickname you must use for an hour.",
            "Take off one piece of clothing (accessories don't count!).",
            "Give the person to your left a 30-second massage.",
            "Kiss the person across from you on the cheek.",
            "Whisper your wildest fantasy to the person next to you.",
            "Do a striptease to a song of the group's choosing.",
            "Feed someone a strawberry in the most seductive way possible.",
            "Let someone blindfold you for 2 minutes.",
            "Give someone a hickey on their neck or arm.",
            "Demonstrate your favorite position using air gestures.",
            "Let someone give you a lap dance.",
            "Kiss someone's hand like you're in a romance novel.",
            "Show the group your best 'come hither' look.",
            "Let someone kiss your neck for 10 seconds.",
            "Describe in detail what you're wearing underneath.",
            "Give someone a sensual shoulder massage.",
            "Let the group choose someone for you to give a passionate kiss to.",
            "Do your best sexy dance for 30 seconds.",
            "Let someone draw a heart on your body with their finger.",
            "Whisper something dirty in someone's ear.",
            "Give someone a strip tease with one item of clothing.",
            "Let someone handcuff you (with safe words established).",
            "Show the group your best smoldering look.",
            "Give someone a slow, passionate kiss on the lips.",
            "Let someone blindfold you and feed you something.",
            "Demonstrate your favorite foreplay move on a pillow.",
            "Give someone a body shot (if drinks are available).",
            "Let someone tickle you while you're blindfolded.",
            "Give the person to your right a lingering hug.",
            "Let someone kiss you anywhere they choose (within reason).",
            "Do your best impression of an adult film star.",
            "Give someone a sensual back scratch.",
            "Let someone write a naughty word on your back and guess what it is.",
            "Give a demonstration of how you like to be kissed on your hand.",
            "Let someone give you a passionate kiss on the neck.",
            "Show the group your best seductive walk.",
            "Give someone a foot massage with lotion.",
            "Let someone take off one item of your clothing.",
            "Whisper your most secret desire to the group.",
            "Give someone a kiss for every round played so far.",
            "Let someone give you a sensual massage for 1 minute.",
            "Demonstrate your best bedroom eyes.",
            "Give someone a slow dance with full body contact.",
            "Let someone tie your hands behind your back for 2 minutes.",
            "Give the group a detailed description of your ideal partner.",
            "Let someone kiss your collarbone.",
            "Do your best stripper pole moves (even without a pole).",
            "Give someone a passionate kiss while the group counts to 10."
        ]
    }
}

NHIE = [
    "Never have I ever... lied to get out of a date.",
    "Never have I ever... snooped through someone else's phone.",
    "Never have I ever... pretended to know a word I didn't understand.",
    "Never have I ever... sent a text to the wrong person and panicked.",
    "Never have I ever... ghosted someone because I didn't want to talk to them.",
    "Never have I ever... had a crush on a teacher.",
    "Never have I ever... peed in a pool.",
    "Never have I ever... faked being sick from work/school.",
    "Never have I ever... stalked an ex on social media.",
    "Never have I ever... eaten food that fell on the floor.",
    "Never have I ever... lied about my age.",
    "Never have I ever... had a one-night stand.",
    "Never have I ever... been arrested.",
    "Never have I ever... cheated on a test.",
    "Never have I ever... had a friends-with-benefits situation.",
    "Never have I ever... gone skinny dipping.",
    "Never have I ever... kissed a stranger.",
    "Never have I ever... snuck out of the house.",
    "Never have I ever... lied to my best friend.",
    "Never have I ever... been fired from a job.",
    "Never have I ever... stolen something from a store.",
    "Never have I ever... had a fake ID.",
    "Never have I ever... been in a physical fight.",
    "Never have I ever... had a crush on a friend's sibling.",
    "Never have I ever... sent a nude photo.",
    "Never have I ever... used a dating app.",
    "Never have I ever... been to a strip club.",
    "Never have I ever... had a paranormal experience.",
    "Never have I ever... broken a bone.",
    "Never have I ever... been in love.",
    "Never have I ever... cried during a movie.",
    "Never have I ever... laughed so hard I peed.",
    "Never have I ever... been drunk in public.",
    "Never have I ever... had a tattoo.",
    "Never have I ever... lied on my resume.",
    "Never have I ever... had surgery.",
    "Never have I ever... traveled abroad.",
    "Never have I ever... been on TV.",
    "Never have I ever... won money from gambling.",
    "Never have I ever... had a pet.",
    "Never have I ever... been to a concert.",
    "Never have I ever... met a celebrity.",
    "Never have I ever... had a car accident.",
    "Never have I ever... been scuba diving.",
    "Never have I ever... eaten sushi.",
    "Never have I ever... gone camping.",
    "Never have I ever... had a professional massage.",
    "Never have I ever... been to a wedding.",
    "Never have I ever... had a surprise party thrown for me.",
    "Never have I ever... dyed my hair a crazy color."
]

WYR = [
    "Would you rather always have to say everything on your mind OR never be able to speak again?",
    "Would you rather have no internet OR no heating/AC?",
    "Would you rather be the funniest person in the room OR the smartest?",
    "Would you rather fight 1 horse-sized duck OR 100 duck-sized horses?",
    "Would you rather know when you die OR how you die?",
    "Would you rather be able to fly OR be invisible?",
    "Would you rather never eat pizza again OR never eat burgers again?",
    "Would you rather have unlimited money OR unlimited love?",
    "Would you rather be famous but poor OR rich but unknown?",
    "Would you rather live forever OR live a normal lifespan but be eternally remembered?",
    "Would you rather have the power to read minds OR teleport anywhere?",
    "Would you rather always be 10 minutes late OR always be 20 minutes early?",
    "Would you rather lose your sense of taste OR your sense of smell?",
    "Would you rather be able to talk to animals OR speak every human language?",
    "Would you rather have a rewind button OR a pause button for your life?",
    "Would you rather always be hot OR always be cold?",
    "Would you rather never be able to use social media again OR never watch TV/movies again?",
    "Would you rather have a third eye OR a third arm?",
    "Would you rather be able to breathe underwater OR fly through the air?",
    "Would you rather have no one show up to your wedding OR your funeral?",
    "Would you rather be allergic to chocolate OR allergic to pizza?",
    "Would you rather have to sing everything you say OR have to dance everywhere you go?",
    "Would you rather be stranded on a deserted island alone OR with someone you hate?",
    "Would you rather have the ability to see 10 minutes into the future OR 150 years into the future?",
    "Would you rather have free Wi-Fi wherever you go OR free coffee wherever you go?",
    "Would you rather be reincarnated as a fly OR just cease to exist after you die?",
    "Would you rather never be able to lie OR never be able to tell when someone is lying?",
    "Would you rather have to wear formal attire every day OR pajamas every day?",
    "Would you rather be the best player on a losing team OR the worst player on a winning team?",
    "Would you rather have unlimited tacos for life OR unlimited sushi for life?",
    "Would you rather have a permanent unibrow OR no eyebrows at all?",
    "Would you rather never use a smartphone again OR never use a computer again?",
    "Would you rather have the hiccups for the rest of your life OR always feel like you need to sneeze?",
    "Would you rather be able to control fire OR control water?",
    "Would you rather have to listen to one song on repeat forever OR only be able to listen to each song once?",
    "Would you rather be poor with lots of good friends OR rich with no friends?",
    "Would you rather have a pet dragon OR a pet unicorn?",
    "Would you rather always have to enter rooms by announcing your name OR always have to do a cartwheel on your way out?",
    "Would you rather have fingers as long as your legs OR legs as short as your fingers?",
    "Would you rather be able to eat anything and have it be perfectly nutritious OR be well-rested with only one hour of sleep?",
    "Would you rather have a clone of yourself OR a robot butler?",
    "Would you rather never have to sleep again OR never have to eat again?",
    "Would you rather be able to control your dreams OR be able to watch your dreams on video the next day?",
    "Would you rather have to wear wet socks for the rest of your life OR have to eat with your feet?",
    "Would you rather have a head the size of a tennis ball OR the size of a watermelon?",
    "Would you rather be able to run at 100 mph OR fly at 10 mph?",
    "Would you rather have to say 'I love you' at the end of every conversation OR never be able to say 'I love you' again?",
    "Would you rather be a famous director OR a famous actor?",
    "Would you rather have a golden voice OR a silver tongue?",
    "Would you rather be in jail for a year OR lose a year of your life?",
    "Would you rather always have to shout OR always have to whisper?"
]

CHEATING = [
    "Is it cheating if you text your ex 'Happy Birthday'?",
    "Is it cheating if you keep a dating app on your phone but don't use it?",
    "Is it cheating if you go on a date with someone else while you are 'taking a break'?",
    "Is it cheating if you like all of your crush's Instagram posts?",
    "Is it cheating if you share a bed with a friend but nothing happens?",
    "Is it cheating if you flirt with someone to get a discount?",
    "Is it cheating if you have an emotional connection with someone online?",
    "Is it cheating if you dance provocatively with someone at a club?",
    "Is it cheating if you keep nudes from an ex?",
    "Is it cheating if you fantasize about someone else while with your partner?",
    "Is it cheating if you have a 'work spouse'?",
    "Is it cheating if you delete text messages so your partner won't see them?",
    "Is it cheating if you go to lunch alone with someone who likes you?",
    "Is it cheating if you use someone else's Netflix password without paying?",
    "Is it cheating if you still have feelings for your ex while in a relationship?",
    "Is it cheating if you watch pornography?",
    "Is it cheating if you have a secret best friend of the opposite gender?",
    "Is it cheating if you compliment someone's appearance?",
    "Is it cheating if you cuddle with a friend while watching a movie?",
    "Is it cheating if you keep in touch with an ex as a friend?",
    "Is it cheating if you send kiss emojis to someone else?",
    "Is it cheating if you have a dating profile just to see who's out there?",
    "Is it cheating if you get a lap dance at a bachelor/bachelorette party?",
    "Is it cheating if you hold hands with someone else?",
    "Is it cheating if you tell someone else your relationship problems?",
    "Is it cheating if you have a crush on a celebrity?",
    "Is it cheating if you check out someone attractive in public?",
    "Is it cheating if you have phone sex with a stranger?",
    "Is it cheating if you kiss someone on the cheek?",
    "Is it cheating if you send anonymous flirty messages online?",
    "Is it cheating if you go to a strip club?",
    "Is it cheating if you have a dating app to make friends?",
    "Is it cheating if you sext with an AI chatbot?",
    "Is it cheating if you dance intimately with someone at a wedding?",
    "Is it cheating if you keep photos of your ex on your phone?",
    "Is it cheating if you have a massage with a happy ending?",
    "Is it cheating if you flirt with the bartender for free drinks?",
    "Is it cheating if you have an emotional affair but no physical contact?",
    "Is it cheating if you kiss someone while drunk?",
    "Is it cheating if you have a separate social media account your partner doesn't know about?",
    "Is it cheating if you send money to an OnlyFans creator?",
    "Is it cheating if you role-play online with someone else?",
    "Is it cheating if you cuddle with a pet more than your partner?",
    "Is it cheating if you have a list of celebrity exceptions?",
    "Is it cheating if you flirt with someone to get ahead at work?",
    "Is it cheating if you keep love letters from an ex?",
    "Is it cheating if you have a crush on your friend's partner?",
    "Is it cheating if you watch videos of your ex?",
    "Is it cheating if you have a separate bank account your partner doesn't know about?",
    "Is it cheating if you tell someone you're single when you're not?"
]

TWENTY_Q_WORDS = [
    {"word": "apple", "category": "Food", "hints": ["It grows on a tree", "It can be red, green, or yellow", "Kept the doctor away"]},
    {"word": "elephant", "category": "Animal", "hints": ["It has a trunk", "It's the largest land mammal", "It has big floppy ears"]},
    {"word": "smartphone", "category": "Technology", "hints": ["You use it every day", "It has a screen", "It fits in your pocket"]},
    {"word": "eiffel tower", "category": "Landmark", "hints": ["It's made of iron", "It's in Europe", "It's in Paris"]},
    {"word": "pizza", "category": "Food", "hints": ["It's baked in an oven", "It has cheese", "It's usually cut into triangles"]},
    {"word": "guitar", "category": "Instrument", "hints": ["It has strings", "You strum or pick it", "It has a hole in the middle"]},
    {"word": "moon", "category": "Space", "hints": ["It orbits the Earth", "It glows at night", "Humans walked on it in 1969"]},
    {"word": "basketball", "category": "Sports", "hints": ["You bounce it", "Played on a court", "Michael Jordan played this"]},
    {"word": "tornado", "category": "Nature", "hints": ["It's a violent storm", "It spins in a funnel", "Common in the Midwest US"]},
    {"word": "pyramid", "category": "Landmark", "hints": ["Ancient structure", "Found in Egypt", "Triangular sides"]},
    {"word": "coffee", "category": "Drink", "hints": ["Made from beans", "Contains caffeine", "Popular morning beverage"]},
    {"word": "butterfly", "category": "Animal", "hints": ["Starts as a caterpillar", "Has colorful wings", "Loves flowers"]},
    {"word": "volcano", "category": "Nature", "hints": ["Mountain that erupts", "Spews lava", "Found in Hawaii and Iceland"]},
    {"word": "airplane", "category": "Transportation", "hints": ["Flies in the sky", "Has wings", "Pilot drives it"]},
    {"word": "chocolate", "category": "Food", "hints": ["Made from cacao", "Can be dark, milk, or white", "Melts in your mouth"]},
    {"word": "rainbow", "category": "Nature", "hints": ["Appears after rain", "Has seven colors", "Arch shape in the sky"]},
    {"word": "refrigerator", "category": "Appliance", "hints": ["Keeps things cold", "Found in kitchens", "Has a freezer compartment"]},
    {"word": "bicycle", "category": "Transportation", "hints": ["Has two wheels", "Human powered", "You pedal it"]},
    {"word": "octopus", "category": "Animal", "hints": ["Lives in the ocean", "Has eight arms", "Can change colors"]},
    {"word": "snowman", "category": "Seasonal", "hints": ["Made of frozen water", "Has a carrot nose", "Melts when warm"]},
    {"word": "telescope", "category": "Science", "hints": ["Used to see far away", "Astronomers use it", "Makes stars closer"]},
    {"word": "umbrella", "category": "Object", "hints": ["Protects from rain", "Opens and closes", "You hold it above your head"]},
    {"word": "submarine", "category": "Vehicle", "hints": ["Travels underwater", "Used by the navy", "Has a periscope"]},
    {"word": "cactus", "category": "Plant", "hints": ["Found in deserts", "Has spines", "Needs little water"]},
    {"word": "fireworks", "category": "Entertainment", "hints": ["Explosive display", "Seen on holidays", "Colorful lights in the sky"]},
    {"word": "microphone", "category": "Technology", "hints": ["Amplifies sound", "Singers use it", "You speak into it"]},
    {"word": "helicopter", "category": "Transportation", "hints": ["Flies in the air", "Has spinning blades", "Can hover in place"]},
    {"word": "glacier", "category": "Nature", "hints": ["Massive ice formation", "Slowly moves", "Found in cold regions"]},
    {"word": "sunglasses", "category": "Accessory", "hints": ["Worn on the face", "Blocks bright light", "Protects your eyes"]},
    {"word": "kangaroo", "category": "Animal", "hints": ["Hops on two legs", "Has a pouch", "Found in Australia"]},
    {"word": "lighthouse", "category": "Structure", "hints": ["Found on coasts", "Has a bright light", "Guides ships"]},
    {"word": "violin", "category": "Instrument", "hints": ["Played with a bow", "Has four strings", "Held under the chin"]},
    {"word": "compass", "category": "Tool", "hints": ["Shows direction", "Has a needle", "Points north"]},
    {"word": "waterfall", "category": "Nature", "hints": ["Water falls from height", "Found in rivers", "Makes a mist"]},
    {"word": "crocodile", "category": "Animal", "hints": ["Lives in water", "Has sharp teeth", "Ancient reptile"]},
    {"word": "satellite", "category": "Space", "hints": ["Orbits Earth", "Sends signals", "Used for TV and GPS"]},
    {"word": "scarecrow", "category": "Farm", "hints": ["Found in fields", "Wears old clothes", "Keeps birds away"]},
    {"word": "binoculars", "category": "Tool", "hints": ["Helps you see far", "Two tubes for eyes", "Used for bird watching"]},
    {"word": "hurricane", "category": "Weather", "hints": ["Massive storm", "Has an eye", "Forms over oceans"]},
    {"word": "trampoline", "category": "Toy", "hints": ["You jump on it", "Stretchy surface", "Found in backyards"]},
    {"word": "saxophone", "category": "Instrument", "hints": ["Brass instrument", "Used in jazz", "Curved shape"]},
    {"word": "igloo", "category": "Shelter", "hints": ["Made of ice blocks", "Found in Arctic", "Dome shaped"]},
    {"word": "windmill", "category": "Structure", "hints": ["Uses wind power", "Has spinning blades", "Found on farms"]},
    {"word": "scorpion", "category": "Animal", "hints": ["Has a stinger tail", "Found in deserts", "Eight legs"]},
    {"word": "telescope", "category": "Science", "hints": ["Looks at stars", "Makes things bigger", "Astronomers use it"]},
    {"word": "cannon", "category": "Weapon", "hints": ["Fires large balls", "Used in old wars", "Needs gunpowder"]},
    {"word": "avalanche", "category": "Nature", "hints": ["Snow slides down mountain", "Very dangerous", "Triggered by sound or movement"]},
    {"word": "parachute", "category": "Equipment", "hints": ["Used when jumping from planes", "Slows your fall", "Made of fabric"]},
    {"word": "subway", "category": "Transportation", "hints": ["Train underground", "Found in cities", "Alternative to traffic"]},
    {"word": "treadmill", "category": "Fitness", "hints": ["Running machine", "Found in gyms", "Goes nowhere"]},
    {"word": "quicksand", "category": "Nature", "hints": ["Wet sand that sinks", "Found near water", "Hard to escape"]}
]